push file

diff --git a/.github/workflows/update-docs.yml b/.github/workflows/update-docs.yml
--- a/.github/workflows/update-docs.yml
+++ b/.github/workflows/update-docs.yml
@@ -39,18 +39,18 @@ jobs:
       - name: Validate OpenAPI Document
         run: npx @scalar/cli document validate docs/openapi.json
 
-      - name: Push to Scalar Registry
-        env:
-          SCALAR_API_TOKEN: ${{ secrets.SCALAR_API_TOKEN }}
-        run: |
-          echo "Authenticating with Scalar..."
-          npx @scalar/cli auth login --token $SCALAR_API_TOKEN
-          
-          echo "Verifying authentication..."
-          npx @scalar/cli auth whoami || echo "Auth verification failed"
-          
-          echo "Publishing to registry..."
-          npx @scalar/cli project publish --slug X8JYjA77V71bS50XcQgmP
+#      - name: Push to Scalar Registry
+#        env:
+#          SCALAR_API_TOKEN: ${{ secrets.SCALAR_API_TOKEN }}
+#        run: |
+#          echo "Authenticating with Scalar..."
+#          npx @scalar/cli auth login --token $SCALAR_API_TOKEN
+#
+#          echo "Verifying authentication..."
+#          npx @scalar/cli auth whoami || echo "Auth verification failed"
+#
+#          echo "Publishing to registry..."
+#          npx @scalar/cli project publish --slug X8JYjA77V71bS50XcQgmP
 #          npx @scalar/cli registry publish docs/openapi.json --namespace default-team-lt6tm --slug ledangtuanbk-test-scalar-sync
 
 
@@ -63,13 +63,13 @@ jobs:
 
 #        run: npx @scalar/cli registry publish --slug ledangtuanbk-test-scalar-sync docs/openapi.json
 
-#      - name: Commit and Push changes
-#        uses: stefanzweifel/git-auto-commit-action@v5
-#        with:
-#          commit_message: "chore: update openapi.json [skip ci]"
-#          file_pattern: docs/openapi.json
-#          branch: docs
-#          create_branch: 'true'
+      - name: Commit and Push changes
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: "chore: update openapi.json [skip ci]"
+          file_pattern: docs/openapi.json
+          branch: docs
+          create_branch: 'true'
 
 #      - name: Publish to Scalar
 #        run: |
